require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/**/*
    - script/*

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Style/AccessModifierDeclarations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - lib/jekyll-github-metadata/site_github_munger.rb
    - spec/edit_link_tag_spec.rb
    - spec/site_github_munger_spec.rb
