sudo: false
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
env:
  matrix:
    - JEKYLL_VERSION=3.1
    - JEKYLL_VERSION=3.2
branches:
  only:
    - master
install:
  - travis_retry script/bootstrap
script: script/cibuild
cache: bundler
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
