sudo: false
language: ruby
rvm:
- 2.1.7
- 2.2
- 2.3.0
matrix:
  include:
    - rvm: 2.1.7
      env: GITHUB_PAGES=83
env:
  matrix:
    - JEKYLL_VERSION=3.1
branches:
  only:
    - master
install:
- travis_retry script/bootstrap
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
