language: ruby
sudo: false
cache: bundler
rvm:
  - &latest_ruby 2.6
  - 2.5
  - 2.4
matrix:
  include:
    - rvm: *latest_ruby
      env: JEKYLL_VERSION=3.7.0
branches:
  only:
    - master

before_install:
  - gem update --system

before_script: bundle update
script: script/cibuild

notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
